"""unify base and add answer constraints

Revision ID: 3720783b8af9
Revises: 8006ef3d0b63
Create Date: 2026-03-12 16:53:08.191815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3720783b8af9'
down_revision: Union[str, Sequence[str], None] = '8006ef3d0b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprehension_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('passage', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("correct_answer IN ('a','b','c','d')", name='ck_comprehension_correct_answer'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprehension_questions_difficulty'), 'comprehension_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_comprehension_questions_id'), 'comprehension_questions', ['id'], unique=False)
    op.create_index(op.f('ix_comprehension_questions_topic'), 'comprehension_questions', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comprehension_questions_topic'), table_name='comprehension_questions')
    op.drop_index(op.f('ix_comprehension_questions_id'), table_name='comprehension_questions')
    op.drop_index(op.f('ix_comprehension_questions_difficulty'), table_name='comprehension_questions')
    op.drop_table('comprehension_questions')
    # ### end Alembic commands ###
