"""create grammar table

Revision ID: 8006ef3d0b63
Revises: 
Create Date: 2026-03-11 17:00:06.287999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8006ef3d0b63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_questions_difficulty'), 'grammar_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_grammar_questions_id'), 'grammar_questions', ['id'], unique=False)
    op.create_index(op.f('ix_grammar_questions_topic'), 'grammar_questions', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grammar_questions_topic'), table_name='grammar_questions')
    op.drop_index(op.f('ix_grammar_questions_id'), table_name='grammar_questions')
    op.drop_index(op.f('ix_grammar_questions_difficulty'), table_name='grammar_questions')
    op.drop_table('grammar_questions')
    # ### end Alembic commands ###
